name: Deploy flask_line_receiver.py to Heroku

on:
  # NOTE: 本 repository は Heroku 用のファイル以外をたくさん含みます。
  #       であれば push trigger は不適切と考えました。
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  deployment-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}  # required
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}  # required
          heroku_email: ${{secrets.HEROKU_EMAIL}}  # required
